### ISSUE TITLE
Error when creating super user in Windows

### ISSUE THREAD

**Issue by jesseleite** [statamic/cli#41]
It'll automatically abort with error when trying to create super user from cli tool in Windows, though you can manually `please make:user` just fine afterwards...

![image](https://user-images.githubusercontent.com/5187394/145112251-8462ca02-a0ca-4fa5-a7e9-07536f3d17fa.png)

Stacktrace...

```
[2021-12-07 19:21:56] local.ERROR: Aborted. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\MissingInputException(code: 0): Aborted. at C:\\wamp64\\www\\test2\\vendor\\symfony\\console\\Helper\\QuestionHelper.php:132)
[stacktrace]
#0 C:\\wamp64\\www\\test2\\vendor\\symfony\\console\\Helper\\QuestionHelper.php(67): Symfony\\Component\\Console\\Helper\\QuestionHelper->doAsk()
#1 C:\\wamp64\\www\\test2\\vendor\\symfony\\console\\Style\\SymfonyStyle.php(361): Symfony\\Component\\Console\\Helper\\QuestionHelper->ask()
#2 C:\\wamp64\\www\\test2\\vendor\\symfony\\console\\Style\\SymfonyStyle.php(258): Symfony\\Component\\Console\\Style\\SymfonyStyle->askQuestion()
#3 C:\\wamp64\\www\\test2\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Concerns\\InteractsWithIO.php(145): Symfony\\Component\\Console\\Style\\SymfonyStyle->ask()
#4 C:\\wamp64\\www\\test2\\vendor\\statamic\\cms\\src\\Console\\Commands\\MakeUser.php(86): Illuminate\\Console\\Command->ask()
#5 C:\\wamp64\\www\\test2\\vendor\\statamic\\cms\\src\\Console\\Commands\\MakeUser.php(72): Statamic\\Console\\Commands\\MakeUser->promptEmail()
#6 C:\\wamp64\\www\\test2\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Statamic\\Console\\Commands\\MakeUser->handle()
#7 C:\\wamp64\\www\\test2\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 C:\\wamp64\\www\\test2\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#9 C:\\wamp64\\www\\test2\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 C:\\wamp64\\www\\test2\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(653): Illuminate\\Container\\BoundMethod::call()
#11 C:\\wamp64\\www\\test2\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(136): Illuminate\\Container\\Container->call()
#12 C:\\wamp64\\www\\test2\\vendor\\symfony\\console\\Command\\Command.php(298): Illuminate\\Console\\Command->execute()
#13 C:\\wamp64\\www\\test2\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#14 C:\\wamp64\\www\\test2\\vendor\\symfony\\console\\Application.php(1005): Illuminate\\Console\\Command->run()
#15 C:\\wamp64\\www\\test2\\vendor\\symfony\\console\\Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#16 C:\\wamp64\\www\\test2\\vendor\\symfony\\console\\Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#17 C:\\wamp64\\www\\test2\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(94): Symfony\\Component\\Console\\Application->run()
#18 C:\\wamp64\\www\\test2\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run()
#19 C:\\wamp64\\www\\test2\\please(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#20 {main}
"} 
```

**Comment by adevade** [comment]
Yep, can confirm! 

![image](https://user-images.githubusercontent.com/1066486/145426252-4a576588-c403-41b2-a374-fd324f15456e.png)
